using System.Collections;
using System.Collections.Generic;

public class jokes
{
    public static string[] so_many_jokes =
    {
        "Why don’t skeletons fight each other? They don’t have the guts.",
        "What did the comforter say after falling off the bed? Oh, sheet!",
        "Why don’t people play more hide-and-seek? Because good players are hard to find.",
        "When is a door not a door? When it’s ajar.",
        "What did the T-rex say to the velociraptor? Nothing, they’re extinct.",
        "Two fish are in a tank. One says to the other, “Any idea how to drive this thing?”",
        "Why shouldn’t you eat clowns? They taste funny.",
        "Spring is here! I got so excited I wet my plants!",
        "Wanna hear a joke about paper? Never mind—it's tearable.",
        "What gets wetter the more it dries? A towel.",
        "What did one ocean say to the other ocean? Nothing, they just waved.",
        "Why did the egg hide? It was a little chicken.",
        "I ordered a chicken and an egg from Amazon. I'll let you know.",
        "Did you hear about the guy whose left side was cut off? He's all right now.",
        "Why did the chicken cross the road? to get away from you, you psycho.",
        "RIP, boiling water. You will be mist.",
        "What do you call a sad strawberry? A blue berry.",
        "Why are pirates called pirates? They just ARRRRR!",
        "What do you get when you cross a polar bear with a seal? A polar bear.",
        "A Freudian slip is when you say one thing but mean your mother.",
        "What do fish say when they hit a concrete wall? Dam!",
        "What do you call a steak that’s been knighted by the queen? Sir Loin.",
        "Why is Peter Pan always flying? Because he Neverlands.",
        "The first rule of the Alzheimer’s club is… Wait, where are we again?",
        "My teachers told me I’d never amount to much since I procrastinate so much. I told them, “Just you wait!”",
        "Did you hear about the cheese factory that exploded in France? There was nothing left but de Brie.",
        "You know why you never see elephants hiding up in trees? Because they’re really good at it.",
        "My wife accused me the other day of being too immature. I told her there were no girls allowed in my fort.",
        "Why was six afraid of seven? Because 7-8-9.",
        "What's black and white and goes round and round? A penguin in the washing machine.",
        "What do you call a dinosaur that crashes his car? Tyrannosaurus Wrecks.",
        "What do you call a bear without any teeth? A gummy bear.",
        "Two guys walked into a bar. The third guy ducked.",
        "Air used to be free at the gas station. Now it's $1.50. You know why? Inflation.",
        "When I was a kid, my mother told me I could be anyone I wanted to be. Turns out, identity theft is a crime.",
        "Why did the picture get arrested? It got framed.",
        "Why can't you tell a taco a secret? They tend to spill the beans!",
        "Dogs can't operate MRI machines. But catscan.",
        "Want to hear a joke about construction? I'm still working on it.",
        "What did one wall say to the other wall? I'll meet you at the corner!",
        "Why don’t eggs tell jokes? Because they might crack up!",
        "How does a train eat? It goes chew, chew!",
        "What do you call fake spaghetti? An impasta!",
        "How do you make a tissue dance? You put a little boogie in it!",
        "What do you call a song about a tortilla? A wrap.",
        "Where do pirates buy hooks? The second hand store.",
        "What’s blue and doesn’t weigh much? Light blue.",
        "What cars do sheep drive? Lamborghinis.",
        "Why didnt the person eat the bannana? it wasnt appealing. ",
        "How do cows learn about current events? They read the moo-spaper.",
        "My dentist appointment is at tooth hurt-y.",
        "Goodbye boiling water, you will be mist.",
        "It takes a lot of guts to be an organ donor.",
        "My ex wife still misses me. BUT HER AIM IS GETTING BETTER!!!",
        "That ghost was such a bad liar…I could see right through him!",
        "Spiders are so smart, they know everything on the web.",
        "I used to have a fear of speed bumps, but I’m slowly getting over it.",
        "I had to get a neck brace last year and I haven’t looked back since.",
        "I told a joke about chemistry, but it didn’t get a reaction.",
        "I’m a big dreamer, so I always hit the snooze button.",
        "I saw the Apple store get robbed…I guess that makes me an iWitness.",
        "That car seems nice, but the muffler looks exhausted.",
        "The ghost told me he’d bring the boos to the party tonight.",
        "I used to hate facial hair, but then it grew on me.",
        "That vampire should see a doctor…he’s always coffin.",
        "I’m following the seafood diet. I see food, then I eat it.",
        "What computer is a singer? A Dell.",
        "My boss wished me a good day, so I went back home.",
        "It’s painful to say this, but I have a bad sore throat.",
        "I only know 25 letters of the alphabet. I don’t know y.",
        "Why did the invisible man decline the job offer? He couldn’t see himself doing it.",
        "How much money is it to park Santa’s sleigh? Nothing. It’s on the house.",
        "I’m so bored at work because all I do is crush cans all day. It’s soda pressing.",
        "3.14% of sailors are considered pi-rates.",
        "What does garlic do before it showers? Takes its cloves off.",
        "Why did the dog float in the water? He was a good buoy.",
        "I invented a pencil with an eraser on each end. There’s no point to it.",
        "What has five toes, a heel, and isn’t your foot? My foot.",
        "I once was addicted to soap, but I’m all clean now.",
        "I made a whopping six figures last year. I also was fired from the toy factory for being too slow.",
        "I got an anonymous compliment about my par king skills today. It said, “Parking fine.”",
        "When two vegetarians get in a fight, is it still called beef?",
        "I heard that 5/4 of people are bad at fractions.",
        "Did you hear the joke about déjà vu? Did you hear the joke about déjà vu?",
        "How does a bee brush its hair? It uses a honeycomb.",
        "If it’s raining cats and dogs, make sure you don’t step in a poodle!",
        "Where do sick boats go to get better? The boat doc.",
        "What has four wheels and flies? A garbage truck.",
        "What’s a lazy kangaroo called? A pouch potato.",
        "What does a pampered cow make? Spoiled milk.",
        "What’s brown and sticky? A stick.",
        "What game are tornadoes the best at? Twister.",
        "What sound does the engine of a witch’s vehicle make? Broooom broooom!",
        "Which bear is the most condescending? A pan-duh!",
        "My girlfriend keeps accusing me of cheating. She's starting to sound like my wife.",
        "I wanted to buy a pair of camouflage pants, but I couldn't find any.",
        "Did you hear about the kidnapping at school? It’s fine, he woke up.",
        "Which state has the most streets? Rhode Island.",
        "Sundays are always a little sad, but the day before is a sadder day.",
        "You’re American when you go into a bathroom and when you come out, but what are you while you’re in the bathroom? European.",
        "I lost my job at the bank on my first day. A woman asked me to check her balance, so I pushed her over.",
        "What kind of music do chiropractors like? Hip pop.",
        "Where do you learn to make ice cream? At sundae school.",
        "Why is cold water so insecure? Because it’s never called hot.",
        "I was going to tell a time-traveling joke, but you guys didn’t like it.",
        "What did the two pieces of bread say on their wedding day? It was loaf at first sight.",
        "What did the drummer call his twin daughters? Anna One, Anna Two!",
        "What do you call two octopuses that look the same? Itenticle.",
        "What has one head, one foot, and four legs? A bed.",
        "What does a house wear? Address.",
        "What’s red and smells like blue paint? Red paint.",
        "I’ve been bored recently, so I decided to take up fencing. The neighbors keep demanding that I put it back.",
        "How do you know when a chicken is evil? It lays deviled eggs.",
        "I told my girlfriend she drew on her eyebrows too high. She seemed surprised.",
        "Why are pigs bad drivers? Because they hog the road.",
        "What did the dad say when his golden retriever was caught eating a hot dog? It's a dog eat dog world out there.",
        "Why did two tall people get along so well? They could really see eye to eye.",
        "Why couldn't the duck be quiet? Because it was addicted to quack.",
        "What is Marco's favorite clothing store? Polo.",
        "What vegetable is kind to everyone? The sweet potato.",
        "What did the geometry teacher say when the class had trouble solving a problem? Let's try a different angle.",
        "Why don't phones ever go hungry? They have plenty of apps to choose from.",
        "Why couldn't the family leave the room after playing with Legos? They were blocked.",
        "What do you give the dentist of the year? A little plaque.",
        "Why did the deer go to the dentist? It had buck teeth.",
        "Why did the Oreo go to the dentist? Because it lost its filling.",
        "Did you hear about the guy who was afraid of hurdles? He got over it.",
        "Did you hear about the guy who drank invisible ink? He's at the hospital waiting to be seen.",
        "What do you call a can opener that doesn't work? A can't opener. ",
        "Why did the computer catch cold? It left a window open.",
        "Why did the employee get fired from the keyboard factory? He wasn't putting in enough shifts.",
    };
}
